# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='post',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
